version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.21.12
    working_directory: ~/code
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y upx
      - run: ./build-release.sh
      - store_artifacts:
          path: bin
          destination: bin
